import asyncio
import contextvars
import os
import uuid
import json
import re
from datetime import datetime, timezone
from typing import Optional, Any
from fastapi import HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.models.analysis import AnalysisHistory
from app.services.log_service import LogService
from app.core.config import settings
from modules.session_db import (
    set_backend, DictBackend, 
    KEY_DXF_JSON, KEY_DXF_PNG_BYTES, KEY_DXF_SVG, 
    KEY_DRAWING_TYPE_CONFIRMED, KEY_DRAWING_BOUNDS, 
    KEY_REVIEW_COMPLETE
)
from modules.dxf_parser import parse_dxf
from modules.svg_renderer import dxf_to_svg, dxf_to_png_bytes, get_drawing_bounds
from modules.drawing_type_predictor import predict_drawing_type
from modules.orchestrator import run_pipeline


def _parse_severity_counts(report: str) -> dict:
    """
    Parse severity counts from the markdown summary table generated by _build_conclusion().
    The orchestrator produces a table in this exact format:
        | 🔴 Nghiêm trọng (High)   | 3 |
        | 🟡 Trung bình (Medium)   | 1 |
        | 🟢 Nhẹ (Low)             | 5 |

    If the table is not found (e.g. older report format), fall back to counting emoji markers.
    Returns a dict with keys 'high', 'medium', 'low'.
    """
    if not report:
        return {"high": 0, "medium": 0, "low": 0}

    def _extract_table_count(pattern: str) -> int:
        """Extract the integer N from a markdown table cell matching `pattern | N |`."""
        m = re.search(pattern + r"\s*\|\s*(\d+)", report, re.IGNORECASE)
        return int(m.group(1)) if m else 0

    # Primary: parse from the _build_conclusion() summary table
    high   = _extract_table_count(r"Nghi[eê]m\s*tr[oọ]ng\s*\(High\)")
    medium = _extract_table_count(r"Trung\s*b[iì]nh\s*\(Medium\)")
    low    = _extract_table_count(r"Nh[eẹ]\s*\(Low\)")

    # Fallback: count emoji occurrences in the body text
    if high == 0 and medium == 0 and low == 0:
        high   = report.count("🔴") + report.count("❗")
        medium = report.count("🟡") + report.count("⚠️")
        low    = report.count("🟢") + report.count("ℹ️")

    return {"high": high, "medium": medium, "low": low}


class AnalysisService:
    # Class-level semaphore shared across all instances/requests
    _semaphore: asyncio.Semaphore | None = None

    @classmethod
    def _get_semaphore(cls) -> asyncio.Semaphore:
        if cls._semaphore is None:
            cls._semaphore = asyncio.Semaphore(settings.MAX_CONCURRENT_TASKS)
        return cls._semaphore

    def __init__(self, db: AsyncSession):
        self.db = db
        self.log_service = LogService(db)

    async def upload_and_parse(self, user_id: int, filename: str, file_bytes: bytes) -> dict:
        """Bước 1: Upload, parse metadata và dự đoán loại bản vẽ."""
        task_id = str(uuid.uuid4())
        
        # 1. Ghi file tạm (ezdxf cần file thật)
        upload_dir = "/tmp/dxf_uploads"
        os.makedirs(upload_dir, exist_ok=True)
        tmp_path = os.path.join(upload_dir, f"{task_id}.dxf")
        
        try:
            with open(tmp_path, "wb") as f:
                f.write(file_bytes)
            
            # 2. Parse & Render (chạy trong executor vì sync/CPU-heavy)
            loop = asyncio.get_event_loop()
            dxf_json = await loop.run_in_executor(None, parse_dxf, tmp_path)
            svg_content = await loop.run_in_executor(None, dxf_to_svg, tmp_path)
            png_bytes = await loop.run_in_executor(None, dxf_to_png_bytes, tmp_path)
            bounds = await loop.run_in_executor(None, get_drawing_bounds, tmp_path)
            
            # 3. Predict Type
            prediction = predict_drawing_type(dxf_json)
            
            # 4. Lưu kết quả vào DB
            metadata = {
                "entity_count": len(dxf_json.get("entities", [])),
                "layer_count": len(dxf_json.get("layers", [])),
                "dimension_count": len(dxf_json.get("dimensions", [])),
                "text_count": len(dxf_json.get("texts", [])),
                "dxf_version": dxf_json.get("metadata", {}).get("dxf_version", "N/A"),
                "bounds": bounds
            }
            
            new_task = AnalysisHistory(
                user_id=user_id,
                task_id=task_id,
                filename=filename,
                status="awaiting_confirmation",
                predicted_type=prediction.drawing_type,
                prediction_confidence=prediction.confidence,
                prediction_reasoning=prediction.reasoning,
                metadata_json=json.dumps(metadata),
                svg_content=svg_content,
                dxf_json=json.dumps(dxf_json),
                png_bytes=png_bytes
            )
            self.db.add(new_task)
            await self.db.commit()
            
            await self.log_service.log(
                event_type="dxf_upload",
                severity="INFO",
                user_id=user_id,
                details={"filename": filename, "task_id": task_id, "predicted_type": prediction.drawing_type}
            )
            
            return {
                "task_id": task_id,
                "predicted_drawing_type": prediction.drawing_type,
                "prediction_confidence": prediction.confidence,
                "prediction_reasoning": prediction.reasoning,
                "is_confident": prediction.is_confident,
                "dxf_metadata": metadata
            }
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    async def confirm_type_and_start(self, task_id: str, drawing_type: str, background_tasks: Any, websocket_manager: Any):
        """Bước 2: Xác nhận loại bản vẽ và bắt đầu phân tích chuyên sâu."""
        stmt = select(AnalysisHistory).where(AnalysisHistory.task_id == task_id)
        result = await self.db.execute(stmt)
        task = result.scalar_one_or_none()
        
        if not task:
            raise HTTPException(status_code=404, detail="Không tìm thấy task")
            
        task.drawing_type = drawing_type
        task.status = "pending" # Đưa vào hàng đợi
        await self.db.commit()
        
        # Bắt đầu background task
        background_tasks.add_task(self.run_analysis, task_id, websocket_manager)
        
        return {"task_id": task_id, "status": "pending", "message": "Đang bắt đầu phân tích..."}

    async def run_analysis(self, task_id: str, websocket_manager=None):
        """Chạy background task phân tích bản vẽ."""
        from app.core.database import AsyncSessionLocal
        
        async with AsyncSessionLocal() as db:
            log_service = LogService(db)
            try:
                async with self._get_semaphore():
                    stmt = select(AnalysisHistory).where(AnalysisHistory.task_id == task_id)
                    result = await db.execute(stmt)
                    task = result.scalar_one_or_none()
                    
                    if not task:
                        return
                        
                    task.status = "running"
                    await db.commit()
                    
                    await log_service.log(
                        event_type="analysis_start",
                        severity="INFO",
                        user_id=task.user_id,
                        details={"task_id": task_id}
                    )
                    
                    # --- Session Bridge Integration ---
                    ctx = DictBackend()
                    # Pre-load data from DB into DictBackend
                    ctx[KEY_DXF_JSON] = json.loads(task.dxf_json) if task.dxf_json else {}
                    ctx[KEY_DXF_PNG_BYTES] = task.png_bytes
                    ctx[KEY_DXF_SVG] = task.svg_content
                    ctx[KEY_DRAWING_TYPE_CONFIRMED] = task.drawing_type
                    
                    metadata = json.loads(task.metadata_json) if task.metadata_json else {}
                    ctx[KEY_DRAWING_BOUNDS] = metadata.get("bounds")
                    
                    set_backend(ctx)
                    
                    try:
                        if websocket_manager:
                            await websocket_manager.send_progress(task_id, "analysis", "Đang phân tích bản vẽ...")
                        
                        # run_pipeline is sync/CPU-heavy — must NOT block event loop.
                        # contextvars.copy_context() ensures the DictBackend set above
                        # is visible inside the executor thread.
                        from modules.rag_engine import get_rag_engine
                        rag_engine = get_rag_engine()  # singleton — already initialized
                        
                        ctx_copy = contextvars.copy_context()
                        loop = asyncio.get_event_loop()
                        response = await loop.run_in_executor(
                            None,
                            ctx_copy.run,
                            run_pipeline,
                            "Bắt đầu phân tích",
                            rag_engine,
                        )
                        
                        # Pull self-check stats from session to populate severity counts
                        from modules.session_db import get_self_check_result
                        sc_res = ctx_copy.run(get_self_check_result)
                        
                        task.status = "completed"
                        task.report_content = response

                        # Parse and persist severity counts from the completed report
                        counts = _parse_severity_counts(response)
                        task.high_errors = counts["high"]
                        task.medium_errors = counts["medium"]
                        task.low_errors = counts["low"]

                        await db.commit()
                        
                        await log_service.log(
                            event_type="analysis_complete",
                            severity="INFO",
                            user_id=task.user_id,
                            details={"task_id": task_id}
                        )
                        
                        if websocket_manager:
                            await websocket_manager.send_result(task_id, {"report": response})
                    finally:
                        set_backend(None)  # Reset backend in current context

            except Exception as e:
                stmt = select(AnalysisHistory).where(AnalysisHistory.task_id == task_id)
                result = await db.execute(stmt)
                task = result.scalar_one_or_none()
                if task:
                    task.status = "failed"
                    task.error_message = str(e)
                    await db.commit()
                    
                    await log_service.log(
                        event_type="analysis_failed",
                        severity="ERROR",
                        user_id=task.user_id,
                        details={"task_id": task_id, "error": str(e)}
                    )
                    
                if websocket_manager:
                    await websocket_manager.send_error(task_id, "ANALYSIS_FAILED", "Lỗi phân tích bản vẽ.")

    async def get_svg(self, task_id: str) -> str:
        stmt = select(AnalysisHistory).where(AnalysisHistory.task_id == task_id)
        result = await self.db.execute(stmt)
        task = result.scalar_one_or_none()
        
        if not task or not task.svg_content:
            raise HTTPException(status_code=404, detail="Không tìm thấy SVG")
            
        return task.svg_content

    async def chat(self, task_id: str, message: str) -> dict:
        """Post-analysis chat handler."""
        stmt = select(AnalysisHistory).where(AnalysisHistory.task_id == task_id)
        result = await self.db.execute(stmt)
        task = result.scalar_one_or_none()
        
        if not task:
            raise HTTPException(status_code=404, detail="Không tìm thấy task")
            
        # Setup session context
        ctx = DictBackend()
        ctx[KEY_DXF_JSON] = json.loads(task.dxf_json) if task.dxf_json else {}
        ctx[KEY_DXF_PNG_BYTES] = task.png_bytes
        ctx[KEY_DRAWING_TYPE_CONFIRMED] = task.drawing_type
        ctx[KEY_REVIEW_COMPLETE] = True  # Trigger RAG chat path in orchestrator
        
        set_backend(ctx)
        try:
            from modules.rag_engine import get_rag_engine
            rag_engine = get_rag_engine()  # singleton — already initialized
            
            # run_pipeline is sync/CPU-heavy — run in executor to avoid blocking event loop
            ctx_copy = contextvars.copy_context()
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                ctx_copy.run,
                run_pipeline,
                message,
                rag_engine,
            )
            return {"reply": response, "task_id": task_id}
        finally:
            set_backend(None)

    async def get_task_status(self, task_id: str) -> dict:
        stmt = select(AnalysisHistory).where(AnalysisHistory.task_id == task_id)
        result = await self.db.execute(stmt)
        task = result.scalar_one_or_none()
        
        if not task:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Không tìm thấy task")
            
        return {
            "task_id": task.task_id,
            "status": task.status,
            "filename": task.filename,
            "progress_step": None,  # populated via WebSocket in real-time
            # Return report content when task is completed so polling fallback can display it
            "result": {"report": task.report_content} if task.status == "completed" and task.report_content else None,
            "error_message": task.error_message
        }

    async def get_history(self, user_id: int, limit: int = 20, offset: int = 0):
        stmt = select(AnalysisHistory).where(
            AnalysisHistory.user_id == user_id,
            AnalysisHistory.status == 'completed'
        ).order_by(AnalysisHistory.created_at.desc()).limit(limit).offset(offset)
        
        result = await self.db.execute(stmt)
        return result.scalars().all()

    async def delete_history(self, history_id: int, user_id: int):
        stmt = select(AnalysisHistory).where(
            AnalysisHistory.id == history_id,
            AnalysisHistory.user_id == user_id
        )
        result = await self.db.execute(stmt)
        history = result.scalar_one_or_none()
        
        if not history:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Không tìm thấy lịch sử")
            
        await self.db.delete(history)
        await self.db.commit()
