"""initial_tables

Revision ID: 79bf66407d31
Revises: 
Create Date: 2026-05-02 18:04:43.181412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bf66407d31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='role_enum'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.Enum('google', 'github', name='oauth_provider_enum'), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('idx_oauth', 'users', ['oauth_provider', 'oauth_id'], unique=False)
    op.create_index('idx_role', 'users', ['role'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', name='severity_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('idx_log_event_type', 'activity_logs', ['event_type'], unique=False)
    op.create_index('idx_log_severity', 'activity_logs', ['severity'], unique=False)
    op.create_index('idx_log_user_id', 'activity_logs', ['user_id'], unique=False)
    op.create_table('analysis_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('drawing_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='status_enum'), nullable=False),
    sa.Column('high_errors', sa.Integer(), nullable=False),
    sa.Column('medium_errors', sa.Integer(), nullable=False),
    sa.Column('low_errors', sa.Integer(), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_analysis_status', 'analysis_history', ['status'], unique=False)
    op.create_index('idx_analysis_task_id', 'analysis_history', ['task_id'], unique=False)
    op.create_index('idx_analysis_user_id', 'analysis_history', ['user_id'], unique=False)
    op.create_table('quota_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('max_requests', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_user_date')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jwt_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jwt_token_hash')
    )
    op.create_index('idx_session_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_session_user_id', 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_user_id', table_name='sessions')
    op.drop_index('idx_session_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('quota_usage')
    op.drop_index('idx_analysis_user_id', table_name='analysis_history')
    op.drop_index('idx_analysis_task_id', table_name='analysis_history')
    op.drop_index('idx_analysis_status', table_name='analysis_history')
    op.drop_table('analysis_history')
    op.drop_index('idx_log_user_id', table_name='activity_logs')
    op.drop_index('idx_log_severity', table_name='activity_logs')
    op.drop_index('idx_log_event_type', table_name='activity_logs')
    op.drop_index('idx_log_created_at', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('idx_role', table_name='users')
    op.drop_index('idx_oauth', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
