"""sync_admin_analysis_fields

Revision ID: 81dcfc20a3c3
Revises: e21142e5a529
Create Date: 2026-05-04 11:09:51.953329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81dcfc20a3c3'
down_revision: Union[str, Sequence[str], None] = 'e21142e5a529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_history', 'svg_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('analysis_history', 'dxf_json',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('analysis_history', 'png_bytes',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_history', 'png_bytes',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
    op.alter_column('analysis_history', 'dxf_json',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('analysis_history', 'svg_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
